name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: discourse/publish-rubygems-action@version2
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
