name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Stuff
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        run: |
          echo "Setting up gem credentials..."
          set +x
          mkdir -p ~/.gem

          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${GITHUB_TOKEN}
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF

          chmod 0600 ~/.gem/credentials
          set -x

          echo "Installing dependencies..."
          gem update bundler
          bundle install

          git config --global user.email "automated@example.com"
          git config --global user.name "Automated Release" && bundle exec rake release

          echo "Running gem release task..."
          release_command="${RELEASE_COMMAND:-rake release}"
          exec $release_command
      # - name: Release Gem
      #   uses: discourse/publish-rubygems-action@v1
      #   env:
      #     RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
      #     RELEASE_COMMAND: |
      #       echo 1 && git config --global user.email "automated@example.com" && git config --global user.name "Automated Release" && bundle exec rake release
